--Task 13
SELECT "STATIONID", "TRUCKTYPE", sum("WASTECOLLECTED") as total_waste_collected
FROM FACTTRIPS as l
LEFT JOIN DIMTRUCK as r
ON l."TRUCKID"=r."TRUCKID"
group by grouping sets ("STATIONID", "TRUCKTYPE");


--Task 14
SELECT "YEAR", "CITY", l."STATIONID", sum("WASTECOLLECTED") as total_waste_collected
FROM FACTTRIPS as l
LEFT JOIN DIMSTATION as r
ON l."STATIONID"=r."STATIONID"
LEFT JOIN DIMDATE as d
ON l."DATEID"=d."DATEID"
GROUP BY ROLLUP ("YEAR", "CITY", l."STATIONID");


--Task 15
SELECT "YEAR", "CITY", l."STATIONID", avg("WASTECOLLECTED") as avg_waste_collected
FROM FACTTRIPS as l
LEFT JOIN DIMSTATION as r
ON l."STATIONID"=r."STATIONID"
LEFT JOIN DIMDATE as d
ON l."DATEID"=d."DATEID"
GROUP BY cube("YEAR", "CITY", l."STATIONID");


--Task 16
CREATE TABLE maxwastestats as 
	(SELECT "CITY", l."STATIONID", "TRUCKTYPE", max("WASTECOLLECTED") as max_waste_collected
	FROM FACTTRIPS as l 
	LEFT JOIN DIMSTATION as r 
	ON l."STATIONID"=r."STATIONID"
	LEFT JOIN DIMTRUCK as d 
	ON l."TRUCKID"=d."TRUCKID"
	GROUP BY ("CITY", l."STATIONID", "TRUCKTYPE")
	)
	
	DATA INITIALLY DEFERRED 
	REFRESH DEFERRED 
	MAINTAINED BY USER;
	

